# Generated by Django 3.2 on 2021-05-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volumeingredient',
            old_name='volume',
            new_name='quantity',
        ),
    ]
